// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: tqt128

#ifndef _TQT128_UI_H
#define _TQT128_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_my_128_png);   // assets\my_128.png
LV_IMG_DECLARE( ui_img_wifi3_png);   // assets\wifi3.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
